/* Server version: WI-V6.3.7.18553 Firebird 2.1 
   SQLDialect: 3. ODS: 11.1. Forced writes: On. Sweep interval: 20000.
   Page size: 16384. Cache pages: 2048 (32768 Kb). Read-only: False. */
SET NAMES NONE;

SET SQL DIALECT 3;

CONNECT 'D:\WORK\KOMUN\tarif\1\TARIF.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE TARIF ADD ID_VIDAB INTEGER;

ALTER TABLE TARIF_MES ADD LICH_PN NUMERIC(15,2);

ALTER TABLE TARIF_MES ADD LICH_PK NUMERIC(15,2);

ALTER TABLE TARIF_MES ADD NOTE VARCHAR(200);

ALTER TABLE TARIF_MES ADD PLOS_BBI NUMERIC(15,2);

ALTER TABLE TARIF_MES ADD NSER_LICH VARCHAR(20);

ALTER TABLE TARIF_MES ADD ID_KOTEL INTEGER;

ALTER TABLE TARIF_MES ADD PLOS_BB NUMERIC(15,2);

ALTER TABLE TARIF_MES ADD MZK NUMERIC(15,2);

ALTER TABLE DOM ALTER COLUMN DOM TYPE VARCHAR(10);

/* Drop table-fields... */
ALTER TABLE TARIF DROP NOTE;


/* Create generator... */
CREATE GENERATOR GEN_SERVICE_ID;


/* Create Primary Key... */
ALTER TABLE DOM ADD CONSTRAINT PK_DOM PRIMARY KEY (ID);

ALTER TABLE DOM_OTHER ADD CONSTRAINT PK_DOM_OTHER PRIMARY KEY (ID);

/* Dropping generators... */
DROP GENERATOR GEN_TARIF_INFO_ID;


